name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build and tomlkit dependencies
        run: python -m pip install --upgrade pip build tomlkit

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version in pyproject.toml
        run: |
          python -c "
          import tomlkit
          with open('pyproject.toml', 'r') as f:
              content = tomlkit.load(f)
          content['project']['version'] = '${{ env.VERSION }}'
          with open('pyproject.toml', 'w') as f:
              tomlkit.dump(content, f)
          "

      - name: Build distribution
        run: python -m build --sdist --wheel --outdir dist/

      - name: Upload release assets using GitHub CLI
        run: |
          gh release upload v${{ env.VERSION }} dist/* --repo ${{ github.repository }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
